# LOGISTIC REGRESSION

### 1. Data Exploration:

a. Load the dataset and perform exploratory data analysis (EDA).

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

b. Examine the features, their types, and summary statistics.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [11]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [12]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

c. Create visualizations such as histograms, box plots, or pair plots to visualize the distributions and relationships between features.
Analyze any patterns or correlations observed in the data.

In [13]:
#Histograms (Distribution of features)
df.hist(figsize=(12,10))
plt.show()

In [14]:
#Box Plot (Outlier detection)
plt.figure(figsize=(12,6))
sns.boxplot(data=df)
plt.show()

In [15]:
#Pair Plot (Relationship between variables)
sns.pairplot(df, hue="Outcome")
plt.show()

In [16]:
#Correlation Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.show()

### 2. Data Preprocessing:

a. Handle missing values (e.g., imputation).

In [17]:
import numpy as np

cols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

for col in cols:
    df[col] = df[col].replace(0, np.nan)
    df[col] = df[col].fillna(df[col].median())

In [18]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

b. Encode categorical variables

In [19]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### 3. Model Building:

a. Build a logistic regression model using appropriate libraries (e.g., scikit-learn).

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
model = LogisticRegression()

b. Train the Model Using Training Data

In [24]:
model.fit(X_train, y_train)

LogisticRegression()

In [25]:
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

print(coefficients)

                    Feature  Coefficient
0               Pregnancies     0.222978
1                   Glucose     1.102682
2             BloodPressure    -0.151540
3             SkinThickness     0.068836
4                   Insulin    -0.138252
5                       BMI     0.688839
6  DiabetesPedigreeFunction     0.203635
7                       Age     0.392410

In [26]:
y_pred = model.predict(X_test)

### 4. Model Evaluation:

a. Evaluate the performance of the model on the testing data using accuracy, precision, recall, F1-score, and ROC-AUC score.
Visualize the ROC curve.

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [28]:
# accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7532467532467533

In [32]:
# precision
Visualize the ROC curve.
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

SyntaxError: invalid syntax (2449791698.py, line 2)

In [33]:
# recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.6181818181818182

In [34]:
#F1-score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.6415094339622641

In [35]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154

In [36]:
#ROC-AUC score.
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:,1]

roc_auc = roc_auc_score(y_test, y_prob)
print("ROC AUC Score:", roc_auc)

ROC AUC Score: 0.82277318640955

In [37]:
#Visualize the ROC curve..
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.plot(fpr, tpr)
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

### 5. Interpretation:

a. Interpret the coefficients of the logistic regression model.

In [38]:
import pandas as pd

coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

print(coefficients)

                    Feature  Coefficient
0               Pregnancies     0.222978
1                   Glucose     1.102682
2             BloodPressure    -0.151540
3             SkinThickness     0.068836
4                   Insulin    -0.138252
5                       BMI     0.688839
6  DiabetesPedigreeFunction     0.203635
7                       Age     0.392410

b. Discuss the significance of features in predicting the target variable (survival probability

From the logistic regression model, some features are more important in predicting diabetes.

Important predictors

1. Glucose

Strongest predictor of diabetes.

Higher glucose levels indicate higher diabetes risk.

2. BMI (Body Mass Index)

Higher BMI increases the probability of diabetes.

Indicates obesity-related risk.

3. Age

Older individuals have a higher probability of diabetes.

4. DiabetesPedigreeFunction

Represents genetic influence.

Higher values indicate stronger hereditary risk.

Less significant features

SkinThickness

Insulin

BloodPressure

These variables may show weaker relationships with the target variable.

# 6. Deployment with Streamlit:

In this task, you will deploy your logistic regression model using Streamlit. The deployment can be done locally or online via Streamlit Share. Your task includes creating a Streamlit app in Python that involves loading your trained model and setting up user inputs for predictions.

In [39]:
import pandas as pd
import pickle
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("diabetes.csv")

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

model = LogisticRegression(max_iter=1000)
model.fit(X, y)

pickle.dump(model, open("diabetes_model.pkl","wb"))

In [40]:
import streamlit as st
import numpy as np
import pickle

model = pickle.load(open("diabetes_model.pkl","rb"))

st.title("Diabetes Prediction System")

preg = st.number_input("Pregnancies")
glucose = st.number_input("Glucose Level")
bp = st.number_input("Blood Pressure")
skin = st.number_input("Skin Thickness")
insulin = st.number_input("Insulin Level")
bmi = st.number_input("BMI")
dpf = st.number_input("Diabetes Pedigree Function")
age = st.number_input("Age")

if st.button("Predict"):

    input_data = np.array([[preg,glucose,bp,skin,insulin,bmi,dpf,age]])

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("High probability of Diabetes")
    else:
        st.success("Low probability of Diabetes")

2026-03-16 19:26:58.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.264 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-16 19:26:58.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

### Interview Questions:

1. What is the difference between precision and recall?

In [ ]:
                                          Simple Difference
Precision	                                              Recall
1.Focuses on prediction accuracy of positive results	   1.Focuses on finding all actual positive cases
2.Important when false positives are costly	               2.Important when missing a positive case is dangerous

2. What is cross-validation, and why is it important in binary classification?

Cross-validation is a technique used to evaluate a machine learning model by training and testing it on different subsets of the dataset to ensure reliable performance.